# @file
# .travis.yml - Drupal 8 Travis CI Integration

language: php

sudo: true

php:
  - 7.1

before_script:
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update
  - composer --verbose install --no-interaction --prefer-source --dev

script:
  - vendor/bin/behat

notifications:
    email:
      recipients:
        - drimma@gmail.com


