# @file
# .travis.yml - Drupal 8 Travis CI Integration

language: php
dist: trusty
sudo: false

php:
  - 7.1

before_install:
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version

install:
  - composer --verbose validate
  - composer --verbose install

script:
  - vendor/bin/behat testing_behat.feature
