# @file
# .travis.yml - Drupal 8 Travis CI Integration

language: php
dist: trusty
sudo: false

php:
  - 7.1

before_script:
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update
  - composer --verbose validate
  - composer --verbose install --dev --prefer-dist

script:
  - bin/behat
